### ISSUE TITLE
New Banlist System Tracking list

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOSalvation-Server#319]
- [ ] The banlist choices in the Host tab is currently sorted in ascending order, which eventually will be an issue after adding more legacy banlists. 

![current banlist sorting](https://puu.sh/uLIMj/44052cda88.png)

The order should be in descending order, however we'll also need the `Goat Format` and `Unlimited` lists on top of legacy banlists, but also below modern banlists.
- [x] Existing pack databases should be replaced with the pack database that I generated
- [x] Sometimes on login, the Deck Edit will read from the 2002 banlist for cards to load up, and it takes a refresh attempt(s) to make it load properly
